# Numpy : Numerical Python

In [1]:
# Def: Numpy is a open source python library used for numerical operations.

# Numpy array are Homogeneous.

# Numpy is designed in C, C++ and Python

In [ ]:
# Interview Question:
# What is the difference between python List and Numpy array?
# 1. List is Heterogeneous, numpy array are Homogeneous
# 2. Numpy array are Faster then python list
# 3. Numpy array runs in parallel on GPU and TPU.
# 4. Dot operator works faster on numpy array

# 1. install, upgrade and import numpy and checking its version

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

# 2. Creating Numpy arrays

In [7]:
# Example-1 : numpy array of integers
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [8]:
# Example-2 : numpy array of float
arr2 = np.array([1.4,2.3,3.5,4.6,5.7])
print(arr2)
print(type(arr2))
print(arr2.dtype)

[1.4 2.3 3.5 4.6 5.7]
<class 'numpy.ndarray'>
float64


In [9]:
# Numpy array are Homogeneous.
# Example-3 : numpy array of float + int
arr3 = np.array([1.4,2.3,3.5,4.6,5.7, 10, 20])
print(arr3)
print(type(arr3))
print(arr3.dtype)

[ 1.4  2.3  3.5  4.6  5.7 10.  20. ]
<class 'numpy.ndarray'>
float64


In [15]:
# Example-4 : numpy array of strings
arr4 = np.array(["Hello", "World@12345"])
print(arr4)
print(type(arr4))
print(arr4.dtype)

# U : unicode : special symbols are allowed in unicode : strings

['Hello' 'World@12345']
<class 'numpy.ndarray'>
<U11


In [17]:
# Example-5 : creating 2D numpy array
arr5 = np.array([[1,2,3], [4,5,6]])
print(arr5)
print(type(arr5))
print(arr5.dtype)
print(arr5.ndim)  # ndim is used to check the dimension of array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
2


In [6]:
# Example-6 : creating 3D numpy array
arr6 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr6)
print(type(arr6))
print(arr6.dtype)
print(arr6.ndim)  # ndim is used to check the dimension of array

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
int64
3


In [7]:
arr6.shape

(3, 2, 3)

# 3. Special type numpy arrays

In [8]:
# array of Zeros

arr_zero = np.zeros(5)  # 1D
print(arr_zero)

[0. 0. 0. 0. 0.]


In [9]:
arr_zero = np.zeros((2,3))  # 2D
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr_zero = np.zeros((2,2,3))  # 2D
print(arr_zero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
# array of Ones
arr_ones = np.ones(5)
print(arr_ones)

[1. 1. 1. 1. 1.]


In [12]:
arr_ones = np.ones((2,5))
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
arr_ones = np.ones((2, 2,5))
print(arr_ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [14]:
# initialize the numpy array with specific value
arr_spe = np.full(5, 100)
print(arr_spe)

[100 100 100 100 100]


In [15]:
arr_spe = np.full((2,5), 100)
print(arr_spe)

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [16]:
arr_spe = np.full((2, 2,5), 100)
print(arr_spe)

[[[100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]]]


In [17]:
# identity matrix is a squared matrix : rows = column
# diagonal values are one and all other zero
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## random package to generate random/synthetic data

In [20]:
# rand() function generate random elements between 0 and 1
np.random.rand(5)  # 1D

array([0.18840334, 0.66675756, 0.4955304 , 0.83388757, 0.14058004])

In [21]:
# 2D 
np.random.rand(2,5) 

array([[0.06984063, 0.70758541, 0.14761634, 0.57718975, 0.75966038],
       [0.43664537, 0.52073817, 0.35528037, 0.08305287, 0.27648094]])

In [24]:
np.random.rand(2,2,5) # 3D

array([[[0.71655756, 0.70334657, 0.61858804, 0.2176243 , 0.86381889],
        [0.64590289, 0.17457659, 0.07328965, 0.22874973, 0.62322965]],

       [[0.13499839, 0.51457915, 0.94154351, 0.35993978, 0.28788763],
        [0.71697939, 0.62636797, 0.1839023 , 0.94597136, 0.21247601]]])

In [26]:
# uniform() function generate uniformaly distributed data
# uniformaly distributed means all values have equal probability to get selected

np.random.uniform(low = 1, high = 100, size = 5)

array([51.07780203, 27.76077371, 60.15667818, 67.69195296, 78.23900717])

In [27]:
np.random.uniform(low = 1, high = 100, size = (2,5))

array([[ 2.19907922,  9.45289627,  4.09808173, 61.85999266, 58.00193488],
       [62.77880112, 79.81567909, 94.86680398, 60.29119559, 28.93334457]])

In [28]:
# random() function just like rand() function

np.random.random((5))

array([0.68348646, 0.08668703, 0.07432113, 0.61621002, 0.04206133])

In [29]:
np.random.random((2,5))

array([[0.95467299, 0.8637079 , 0.20041774, 0.90978893, 0.67613684],
       [0.55602805, 0.49296646, 0.28842663, 0.70841933, 0.95648576]])

In [34]:
# randn() : standard normal distrubution function. mean = 0, SD = 1
# 99.7% values will be between -3 to + 3

np.random.randn(10)

array([-0.01381919, -0.60760629, -0.96315431,  0.16133909,  1.46359947,
       -0.47015282, -0.63314733, -0.75129915, -0.08297513, -0.47888082])

In [35]:
np.random.randn(2,5)

array([[-1.01372459,  1.2336584 ,  1.17793565,  0.29445925, -0.56440172],
       [-0.02065169,  0.92533526, -0.67932277, -0.03817384, -0.25264933]])

In [36]:
np.random.randn(3, 2,5)

array([[[ 1.25111376e+00,  2.19817646e+00,  7.99605161e-01,
          1.01277037e+00, -1.25915011e+00],
        [-1.36803888e+00,  3.12720079e-03,  7.57391205e-01,
          2.56917614e-01, -5.27138216e-01]],

       [[ 4.15618554e-01,  1.33673665e+00,  7.95165995e-01,
          3.93560451e-04, -5.84149589e-01],
        [ 2.20795748e-01,  1.58563847e+00,  8.47616260e-01,
          1.89954563e-03, -8.90869070e-01]],

       [[ 1.38457509e+00, -6.50108078e-01, -1.42146838e+00,
          1.84864841e-02, -8.49623149e-01],
        [ 9.45160610e-01, -1.49930143e+00, -4.70762131e-01,
         -1.34187183e-01, -6.14568530e-01]]])

In [38]:
# normal(): normal distributed: here mean & SD can be different from 0 and 1
# loc = mean, scale = SD
np.random.normal(loc = 5, scale = 1.2, size = 10)

array([5.77433647, 4.93351259, 6.02699737, 6.99651886, 3.03101383,
       2.31878899, 6.88242988, 4.35070227, 5.07837134, 4.09382573])

In [39]:
np.random.normal(loc = 5, scale = 1.2, size = (2,5))

array([[5.35044705, 5.09041478, 4.56959581, 4.84929004, 6.59053383],
       [5.38335735, 4.37128508, 5.97697322, 7.13333202, 3.70843938]])

In [40]:
# randn()  vs normal()

In [46]:
# choice() function is used for categorical data
np.random.seed(42)
np.random.choice(['Paradise', 'Fauzi', 'Spirit', 'Puspa', 'bahubali'], size = 3)

array(['Puspa', 'bahubali', 'Spirit'], dtype='<U8')

In [48]:
np.random.choice(['Paradise', 'Fauzi', 'Spirit', 'Puspa', 'bahubali'], p = [0.2, 0.05, 0.05, 0.1, 0.6],  size = 10)

array(['bahubali', 'bahubali', 'bahubali', 'Paradise', 'bahubali',
       'Puspa', 'Paradise', 'bahubali', 'Paradise', 'bahubali'],
      dtype='<U8')

### creating sequences, shuffle, Permutation and lineraly separated data

In [2]:
# arange() function is used for creating a sequence of elements 
# arange() is just similar to range() function
import numpy as np
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr1 = np.arange(1, 10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [4]:
arr1 = np.arange(1, 10, 2)
print(arr1)

[1 3 5 7 9]


In [6]:
# shuffle() : used for shuffle the elements
# shuffle() perform inplace operation
# shuffle() will modify the orignal array
arr1 = np.arange(10)
print(arr1)

np.random.shuffle(arr1)
arr1

[0 1 2 3 4 5 6 7 8 9]


array([9, 1, 2, 5, 4, 7, 8, 0, 3, 6])

In [8]:
# permutation() : shuffle elements but return new shuffled array
# this don't modify the original array
arr1 = np.arange(10)
print(arr1)

arr2 = np.random.permutation(arr1)
print(arr2)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[5 8 6 0 1 7 3 4 2 9]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# linspace() : linearly spaced array
# linspace(start, end, number of elements)

arr3 = np.linspace(1, 10, 10)   
print(arr3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
arr3 = np.linspace(1, 10, 4)   
print(arr3)

[ 1.  4.  7. 10.]


In [13]:
arr3 = np.linspace(1, 10, 100)   
print(arr3)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

# 4. Array shape, Reshape and transpose

In [16]:
south_famous_dresses = np.array([["Lungi", "Dhoti", "Kurta"],["Saree", "Anarkali", "Half Saree"]])

print(south_famous_dresses)
print(south_famous_dresses.shape)

[['Lungi' 'Dhoti' 'Kurta']
 ['Saree' 'Anarkali' 'Half Saree']]
(2, 3)


In [17]:
updated_arr = south_famous_dresses.reshape(3,2)
print(updated_arr)

[['Lungi' 'Dhoti']
 ['Kurta' 'Saree']
 ['Anarkali' 'Half Saree']]


In [18]:
updated_arr = south_famous_dresses.reshape(1,6)
print(updated_arr)

[['Lungi' 'Dhoti' 'Kurta' 'Saree' 'Anarkali' 'Half Saree']]


In [22]:
updated_arr = south_famous_dresses.reshape(1,2,1,3)
print(updated_arr)

[[[['Lungi' 'Dhoti' 'Kurta']]

  [['Saree' 'Anarkali' 'Half Saree']]]]


In [23]:
# while reshaping number of elements must be same 

In [24]:
# ravel() : used for flatten the array, means convert any array to 1D array

arr4 = south_famous_dresses.ravel()
print(arr4)

['Lungi' 'Dhoti' 'Kurta' 'Saree' 'Anarkali' 'Half Saree']


In [27]:
# transpose : convert Row -> Columns  & Colums -> Row
print(south_famous_dresses)
print(south_famous_dresses.T)

[['Lungi' 'Dhoti' 'Kurta']
 ['Saree' 'Anarkali' 'Half Saree']]
[['Lungi' 'Saree']
 ['Dhoti' 'Anarkali']
 ['Kurta' 'Half Saree']]


# 5. Size and Data type of numpy array

In [28]:
counting_telugu = np.array(["Okati", "Rendu", "Mudu", "Nalgu", "idu"])

print(counting_telugu.size)

5


In [29]:
print(counting_telugu.dtype)

<U5


In [41]:
# astype() : datatype conversion
arr6 = np.array([0, -20, 60.6, 40.3]).astype(bool)

print(arr6)
print(arr6.dtype)

[False  True  True  True]
bool


In [34]:
arr6 = np.array(["10", "20", "60", "40"]).astype(float)

print(arr6)
print(arr6.dtype)

[10. 20. 60. 40.]
float64


In [35]:
arr6 = np.array([True, False, True, True]).astype(int)

print(arr6)
print(arr6.dtype)

[1 0 1 1]
int64


# 6. Indexing & slicing & Modification

In [1]:
import numpy as np
south_sweet = np.array([["Motichoor", "Kalakand", "Jalebi"],
                        ["Bobbatlu", "Kaji Kaya", "Khaja"]])

print(south_sweet[0][0])

Motichoor


In [2]:
print(south_sweet[0])

['Motichoor' 'Kalakand' 'Jalebi']


In [3]:
print(south_sweet[1,1:3])  # [row, range]

['Kaji Kaya' 'Khaja']


In [4]:
print(south_sweet[0,1:3])  # [row, range]

['Kalakand' 'Jalebi']


In [5]:
print(south_sweet[0,:2])  # [row, range]

['Motichoor' 'Kalakand']


In [6]:
south_sweet = np.array([["Motichoor", "Kalakand", "Jalebi"],
                        ["Bobbatlu", "Kaji Kaya", "Khaja"]])

print(south_sweet[:1,:2])  # [row, range]

[['Motichoor' 'Kalakand']]


In [7]:
print(south_sweet[-1, -2])

Kaji Kaya


In [8]:
print(south_sweet[-1:, -1:-2:-1])

[['Khaja']]


# Modifications, insertion and deletion in numpy

In [10]:
import numpy as np
south_sweet = np.array([["Motichoor", "Kalakand", "Jalebi"],
                        ["Bobbatlu", "Kaji Kaya", "Khaja"]])

# Modification of single element
south_sweet[0,0] = 'Payasum'
print(south_sweet)

[['Payasum' 'Kalakand' 'Jalebi']
 ['Bobbatlu' 'Kaji Kaya' 'Khaja']]


In [13]:
# updated complete row
south_sweet[1] = ['Kesari', 'Pulareddy', 'arasalu']
print(south_sweet)

[['Payasum' 'Kalakand' 'Jalebi']
 ['Kesari' 'Pulareddy' 'arasalu']]


In [16]:
# update the complete column
# numpy array take fix space to store data
south_sweet[:, 2] = ['Mysurepak', 'Doublekamitha']
print(south_sweet)

[['Payasum' 'Kalakand' 'Mysurepak']
 ['Kesari' 'Pulareddy' 'Doublekam']]


In [17]:
# Insert operation : New row

south_sweet = np.insert(south_sweet, 1, ['Gajarpak', 'Rusmali', 'Firni'], axis = 0)
print(south_sweet)

[['Payasum' 'Kalakand' 'Mysurepak']
 ['Gajarpak' 'Rusmali' 'Firni']
 ['Kesari' 'Pulareddy' 'Doublekam']]


In [18]:
# Insert operation : New column

south_sweet = np.insert(south_sweet, 2, ['rasbhari', 'Gulabjamun', 'Kheer'], axis = 1)
print(south_sweet)

[['Payasum' 'Kalakand' 'rasbhari' 'Mysurepak']
 ['Gajarpak' 'Rusmali' 'Gulabjamu' 'Firni']
 ['Kesari' 'Pulareddy' 'Kheer' 'Doublekam']]


In [19]:
# Insert operation : multiple columns

south_sweet = np.insert(south_sweet, 2, 
                        [['Kajukatli', 'Ghevar', 'Peda'],['Kajukatli', 'Ghevar', 'Peda'] ], 
                        axis = 1)
print(south_sweet)

[['Payasum' 'Kalakand' 'Kajukatli' 'Kajukatli' 'rasbhari' 'Mysurepak']
 ['Gajarpak' 'Rusmali' 'Ghevar' 'Ghevar' 'Gulabjamu' 'Firni']
 ['Kesari' 'Pulareddy' 'Peda' 'Peda' 'Kheer' 'Doublekam']]


In [20]:
# Delete operation 
south_sweet = np.delete(south_sweet, 0, axis = 0)
print(south_sweet)

[['Gajarpak' 'Rusmali' 'Ghevar' 'Ghevar' 'Gulabjamu' 'Firni']
 ['Kesari' 'Pulareddy' 'Peda' 'Peda' 'Kheer' 'Doublekam']]


In [21]:
# Delete operation : column
south_sweet = np.delete(south_sweet, 2, axis = 1)
print(south_sweet)

[['Gajarpak' 'Rusmali' 'Ghevar' 'Gulabjamu' 'Firni']
 ['Kesari' 'Pulareddy' 'Peda' 'Kheer' 'Doublekam']]


In [25]:
# Delete operation : column
south_sweet = np.delete(south_sweet, [1,3], axis = 1)
print(south_sweet)

[['Gajarpak' 'Ghevar' 'Firni']
 ['Kesari' 'Peda' 'Doublekam']]


# 7. Mathematical & Statistical operations

In [26]:
sweet_price = np.array([[450, 600, 400], [850, 400, 250]])
print(sweet_price + 100)

[[550 700 500]
 [950 500 350]]


In [27]:
print(sweet_price * 2)

[[ 900 1200  800]
 [1700  800  500]]


In [28]:
np.sum(sweet_price)

np.int64(2950)

In [30]:
print(np.min(sweet_price))

250


In [31]:
print(np.max(sweet_price))

850


In [32]:
print(np.mean(sweet_price))

491.6666666666667


In [33]:
print(np.var(sweet_price))

36180.555555555555


In [34]:
# standard deviation:  how much the data far away from the mean
print(np.std(sweet_price))

190.21187017522212


In [39]:
# 50% of the people are below 425
print(np.percentile(sweet_price, 50))

425.0


In [40]:
sweet_price = np.array([[450, 600, 400], [850, 400, 250]])

In [41]:
# quantile is special type of percentile
np.quantile(sweet_price, 0.50)

np.float64(425.0)

In [46]:
# return the index of largest value
age = [22, 16, 500, 14, 8, 20, 90, 200]
np.argmax(age)

np.int64(2)

In [47]:
# return the index of smallest value
age = [22, 16, 500, 14, 8, 20, 90, 200]
np.argmin(age)

np.int64(4)

In [48]:
np.sqrt(900)

np.float64(30.0)

In [50]:
pi = 3.142367459245
np.round(pi, 3)

np.float64(3.142)

In [51]:
np.floor(pi)

np.float64(3.0)

In [52]:
np.ceil(pi)

np.float64(4.0)

In [53]:
np.abs(-19)

np.int64(19)

In [1]:
import numpy as np

In [2]:
# sort operation
arr1 = np.array([60, 50, 20, 10, 100, 90])
print(arr1)

[ 60  50  20  10 100  90]


In [3]:
print(np.sort(arr1))

[ 10  20  50  60  90 100]


In [4]:
# reverse sort
print(np.sort(arr1)[::-1])

[100  90  60  50  20  10]


In [10]:
# sorting a string array
# sorting in ASCII format
# A-Z starts with 65-90, a-z => 97 - 122
arr2 = np.array(["Orange", "aapple", "anana"])
print(np.sort(arr2))

['Orange' 'aapple' 'anana']


# 8. Concatenation, Stacking, Splitting numpy arrays

In [12]:
# concatenate the 1d's array's

arr1 = np.array([100, 200, 300])
arr2 = np.array([90, 150, 5])
arr3 = np.array([10, 20, 30])

new_arr = np.concatenate((arr1, arr2, arr3))
print(new_arr)

[100 200 300  90 150   5  10  20  30]


In [15]:
# concatenate the 2D arrays

arr1 = np.array([[10, 20, 30],
                 [40, 50, 60]])

arr2 = np.array([[100, 200, 300],
                 [400, 500, 600]])

# Vertical concatenation : Row wise
new_2d_arr = np.concatenate((arr1, arr2), axis = 0)
print(new_2d_arr)

[[ 10  20  30]
 [ 40  50  60]
 [100 200 300]
 [400 500 600]]


In [16]:
# Horizontal concatenation : Column wise
new_2d_arr = np.concatenate((arr1, arr2), axis = 1)
print(new_2d_arr)

[[ 10  20  30 100 200 300]
 [ 40  50  60 400 500 600]]


In [22]:
# We cannot concatenate 1D & 2D arrays
# We can vertically concatenate the 2D's array of different shape

arr1 = np.array([[100, 200, 300]])
arr2 = np.array([[100, 200, 300],
                 [400, 500, 600]])

# Vertical concatenation : Row wise
new_2d_arr = np.concatenate((arr1, arr2), axis = 0)
print(new_2d_arr)

[[100 200 300]
 [100 200 300]
 [400 500 600]]


In [19]:
# Horizontally concatenation
new_2d_arr = np.concatenate((arr1, arr2), axis = 1)
print(new_2d_arr)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [23]:
arr1 = np.array([[100, 200],
                [300, 400]])
arr2 = np.array([[100, 200, 300],
                 [400, 500, 600]])

# Horizontally concatenation
new_2d_arr = np.concatenate((arr1, arr2), axis = 1)
print(new_2d_arr)

[[100 200 100 200 300]
 [300 400 400 500 600]]


# np.stack() function

In [24]:
# stack() function will add a "NEW DIMENSION" 
# Stack Vs Concatenate
# Concatenate don't add the new dimension while Stack add the new dimension

In [25]:
arr1 = np.array([1000, 2000, 3000])
arr2 = np.array([300, 200, 100])

stacked_arr = np.stack((arr1, arr2))
print(stacked_arr)

[[1000 2000 3000]
 [ 300  200  100]]


In [27]:
stacked_arr = np.stack((arr1, arr2), axis = 1)
print(stacked_arr)
print(stacked_arr.shape)

[[1000  300]
 [2000  200]
 [3000  100]]
(3, 2)


# vstack() : vertical stacking
# same as vertical concatenation

In [28]:
arr1 = np.array([[10, 20, 30],
                 [40, 50, 60]])

arr2 = np.array([[100, 200, 300],
                 [400, 500, 600]])

vstack_arr = np.vstack((arr1, arr2))
print(vstack_arr)

[[ 10  20  30]
 [ 40  50  60]
 [100 200 300]
 [400 500 600]]


# hstack() : horizontal stacking

#same as horizontal concatenation

In [29]:
arr1 = np.array([[10, 20, 30],
                 [40, 50, 60]])

arr2 = np.array([[100, 200, 300],
                 [400, 500, 600]])

hstack_arr = np.hstack((arr1, arr2))
print(hstack_arr)

[[ 10  20  30 100 200 300]
 [ 40  50  60 400 500 600]]


# splitting numpy array

In [36]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80,90, 100])

split_arr = np.split(arr1, 2)
print(split_arr)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [37]:
split_arr[0]

array([10, 20, 30, 40, 50])

In [38]:
split_arr[0][2]

np.int64(30)

In [39]:
arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80,90]])

split_arr = np.split(arr1, 3)
print(split_arr)

[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]])]


In [41]:
split_arr[1]

array([[40, 50, 60]])

In [42]:
split_arr[1][0]

array([40, 50, 60])

In [43]:
split_arr[1][0][2]

np.int64(60)

In [44]:
split_arr[2][0][1]

np.int64(80)